# This is for a single stage build Not preferable for industrial level requirements
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
COPY requirements-dev.txt .

RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

COPY app.py calculator.py pytest.ini .
COPY tests/ ./tests/

RUN mkdir -p reports

CMD ["python", "app.py", "health"]