
FROM python:3.10-slim AS builder

WORKDIR /app

COPY requirements.txt .
COPY requirements-dev.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .

RUN python -m pytest tests/


# Stage 2 - Runtime

FROM python:3.10-slim

WORKDIR /app

COPY app.py .
COPY calculator.py .

CMD ["python", "app.py", "health"]